### ISSUE TITLE
 package conflict with http-server

### ISSUE THREAD

**Issue by arete** [ajay-gandhi/hs#1]
hi, you package conflict with http-server
# https://github.com/indexzero/http-server/issues/243

**Comment by ajay-gandhi** [comment]
The `hs` shell command is listed in the package.json file for [this package](https://github.com/ajay-gandhi/hs/blob/master/package.json) and [http-server](https://github.com/indexzero/http-server/blob/master/package.json).

I'll add another alias for this package soon.
